@startuml
title Контекстная диаграмма АгроТех мониторинг животноводства (распределенная)

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ==='
Person(operator, "Персонал", "Мониторинг состояния животных")
Person(admin, "Администраторы", "Управление системой")

' === Cистемы ==='
System(agrotech_central_server, "Центральный сервер", "Центральный сервер системы который ведет общую аналитику системы и синхронизирует данные между агентами")
System(agrotech_system_agent_1, "Сервер-агент 1", "Система выполняет мониторинг состояния скота, управляет системами кормления скота, оповещает о нештатных ситуациях на ферме")
System(agrotech_system_agent_n, "Сервер-агент N", "Система выполняет мониторинг состояния скота, управляет системами кормления скота, оповещает о нештатных ситуациях на ферме")

' === Внешние системы ==='
System_Ext(device_controllers, "Система управления устройствами", "Внешняя система управления устройствами на ферме")
System_Ext(metrics_consumer, "Система потребления метрик", "Внешняя система потребления метрик")
System_Ext(client, "Клиенты системы", "Клиенты системы веб или мобильные приложения")
System_Ext(notification_system, "Система уведомлений", "Внешняя система отправки уведомлений")

' === Отношения ==='
Rel(admin, agrotech_central_server,"Управляет системой")
Rel(admin, agrotech_system_agent_1,"Управляет системой")
Rel(admin,agrotech_system_agent_n,"Управляет системой")

Rel(operator, agrotech_system_agent_1, "Пользуется системой")
Rel(operator, agrotech_system_agent_n, "Пользуется системой")

Rel(agrotech_system_agent_1,notification_system,"Отправляет уведомления")
Rel(agrotech_system_agent_1, agrotech_central_server, "Отправляет данные на центральный сервер")
Rel(agrotech_system_agent_1,metrics_consumer,"Предоставляет метрики потребителям")
Rel(agrotech_system_agent_1,device_controllers,"Управляет устройствами")

Rel(agrotech_system_agent_n, agrotech_central_server, "Пользуется системой")
Rel(agrotech_system_agent_n,notification_system,"Отправляет данные на центральный сервер")
Rel(agrotech_system_agent_n,metrics_consumer,"Предоставляет метрики потребителям")
Rel(agrotech_system_agent_n,device_controllers,"Управляет устройствами")


Rel(agrotech_central_server,notification_system,"Отправляет уведомления")
Rel(agrotech_central_server,metrics_consumer,"Предоставляет метрики потребителям")

Rel(client, agrotech_system_agent_1,"Взаимодействует с системой через API")
Rel(client, agrotech_system_agent_n,"Взаимодействует с системой через API")
Rel(client, agrotech_central_server,"Взаимодействует с системой через API")




@enduml